### PR TITLE
Fix small bugs in a notebook (tutorial1)

### PR DESCRIPTION
**Pull request by gui-miotto**
The version of tutorial1 shown [here](https://openpiv.readthedocs.io/en/latest/src/tutorial1.html) does not run. But the one under `examples` does. This PR simply replaces the version under `docs` by the version under `examples`.

### CODE REVIEW

**Comment by alexlib** [comment]
thanks @gui-miotto

**Comment by gui-miotto** [comment]
welcome @alexlib 
I think now someone has to run a sphinx build to update the webpage, right?

**Comment by alexlib** [comment]
It is readthedocs job. Will check

**Comment by gui-miotto** [comment]
Great, it has been updated. :-)

**Pull request merged**
