### PR TITLE
Window deformation

### PR DESCRIPTION
**Pull request by TKaeufer**
I added multipass interrogation and window deformation to Open PIV. The additional functions are written in python. Start the OpenPIV_windef_client to set up the PIV interrogation. I also added a little notebook that compares the extended search_piv and widim with the new window deformation.
@alexlib

### CODE REVIEW

**Comment by alexlib** [comment]
@TKaeufer 

something is wrong with the package: 
/windef is a sub-folder under examples/notebooks but we shall expect it to be in the main directory and not as a separate folder

I suggest to have windef.py in the /openpiv folder
and windef.ipynb in notebooks
all the tests under tests/ folder
additional functions accordingly - if it's a .pyx file - then under /openpiv

**Comment by TKaeufer** [comment]
Thank you for your reply. I had some issues with the import of the windef function for the test and the notebook. Since I have not installed the new functions, I cannot import them from the anaconda library. I tried to set a different import path but the only way I got it working was to copy the functions to the same folder as the notebook and the test and do a local import.
Therefore, I copied the functions once in the openpiv/, once in openpiv/example/notebook/windef/, and some of the functions which are needed for the test also in openpiv/test/. I guess this is not the most elegant way, but I quickly tested it and now it seems to all work and the multipass with window deformation can be tested can get tested. I guess the import issue will be solved once the new functions are installed in the anaconda library.
I'm glad for any feedback.
@alexlib

**Comment by alexlib** [comment]
but this directory is not necessary anymore, right? 

https://github.com/TKaeufer/openpiv-python/tree/window-deformation/openpiv/examples/notebooks/windef

**Comment by TKaeufer** [comment]
It is still necessary because it contains the notebook "windef_comparison.ipynb". In this notebook, I copied the new PIV with the window deformation, the extended search area PIV and the widim PIV to allow a quick visual comparison of the vector fields.

**Comment by alexlib** [comment]
> It is still necessary because it contains the notebook "windef_comparison.ipynb". In this notebook, I copied the new PIV with the window deformation, the extended search area PIV and the widim PIV to allow a quick visual comparison of the vector fields.

1. please move the notebook to notebooks
2. we do not need the folder test1 twice - you can use the existing one
3. please move all .py files to /openpiv
4. remove functions and .py files lowercase, no need `openpiv` before the name
5. maybe it is better to consolidate everything in a single file - then it'll be clearly belonging to the same namespace `openpiv.windef`

**Comment by alexlib** [comment]
> > It is still necessary because it contains the notebook "windef_comparison.ipynb". In this notebook, I copied the new PIV with the window deformation, the extended search area PIV and the widim PIV to allow a quick visual comparison of the vector fields.
> 
> 1. please move the notebook to notebooks
> 2. we do not need the folder test1 twice - you can use the existing one
> 3. please move all .py files to /openpiv
> 4. remove functions and .py files lowercase, no need `openpiv` before the name
> 5. maybe it is better to consolidate everything in a single file - then it'll be clearly belonging to the same namespace `openpiv.windef`

see the suggestion here https://github.com/alexlib/openpiv-python/tree/window-deformation

**Comment by TKaeufer** [comment]
> 
> 
> > > It is still necessary because it contains the notebook "windef_comparison.ipynb". In this notebook, I copied the new PIV with the window deformation, the extended search area PIV and the widim PIV to allow a quick visual comparison of the vector fields.
> > 
> > 
> > 
> > 1. please move the notebook to notebooks
> > 2. we do not need the folder test1 twice - you can use the existing one
> > 3. please move all .py files to /openpiv
> > 4. remove functions and .py files lowercase, no need `openpiv` before the name
> > 5. maybe it is better to consolidate everything in a single file - then it'll be clearly belonging to the same namespace `openpiv.windef`
> 
> see the suggestion here https://github.com/alexlib/openpiv-python/tree/window-deformation

Thank you for that suggestion. I think it is a good idea to store all the additional and modified functions for the window deformation. But I also think it would be a good idea to also have a user interface in a separate file (like the third entry in the windef_comparison notebook). I created this user interface for non-expert users. It takes a while to understand all the OpenPIV functions and settings (at least it took a while for me). My goal was to simplify this a little bit by showing the user just the user interface and giving him the information about what the settings change and mean. By putting this together with all the functions this effect gets, in my opinion, somewhat nullified.  If a user wants to learn more about the code, it is easy for him to access the imported files by pressing "control+G" (at least with spyder). 
I will work on the shape issue tonight!

**Comment by alexlib** [comment]
Dear @TKaeufer - i appreciate a lot your effort - but we cannot pull this request into openpiv, simply because it kind of destroying the history of the files (`setup.py` and all others). This will create a mess if we'll need to find an old bug and trace it's origin to some specific commit. 
I understand that you did a fresh restart by removing all files and copying over, unfortunately this is not the right way. The right way would be :
1. clone the master branch (to which you later want to send your work) from the openpiv/openpiv-python
2. take a branch from the master, e.g. `new_submission`
3. create manually difference (using some text editor that allows to compare code line by line) of your branch `window-deformation` with the `new_submission` and applying only differences to the new branch. 
3. `git add .`, `git commit -m "new submission of the window-deformation`, `git push` (to your repository under the new branch) and then pull request from the new branch

Thanks
Alex

PS. Meanwhile I installed your branch and try to run it to see whether something is wrong. Please tell me if the above steps are cumbersome - I can do it for you if needed.

**Comment by alexlib** [comment]
I confirm that everything works as expected. 

I suggest to move user_interface... to examples/tutorials and rename it to example_windef_run.py to make it more accessible. (it will require to change the paths to `../test1` but it's even simpler :) 

the notebook work nicely, great job

**Comment by TKaeufer** [comment]
Thank you! I understand the issue. Therefore, I created a new pull request.
https://github.com/OpenPIV/openpiv-python/pull/115
I hope everything is fine now.

**Pull request closed without merging**
