### PR TITLE
A change in overlap setting.

### PR DESCRIPTION
**Pull request by JUDEKEPA**
### Main idea
The former <code>overlap</code> verification condition is that it is not allowed to larger or equal to <code>window_size</code>. It works well when <code>window_size</code> is equal to <code>search_area_size</code>, and any different spacing can be set for window centres (pixels of interest). But when <code>search_area_size</code> is larger than <code>window_size</code>, the largest overlap between each search window is the <code>window_size - 1</code>. That makes the window centres spacing cannot be smaller than <code>search_area_size - window_size</code>.

### Here is an example:
1. When the verification condition is <code>overlap</code> is not allowed to larger or equal to <code>window_size</code>.
<code>window_size = 32
search_area_size = 35
overlap = 33</code>
Output: **ValueError**("Overlap has to be smaller than the window_size")

The largest overlap can be set at 31 In this situation, the spacing between each window centre is 4.

2. When the verification condition is <code>overlap</code> is not allowed to larger or equal to <code>search_area_size</code>.
<code>window_size = 32
search_area_size = 35
overlap = 34</code>

This time, the spacing between each window centre is 0. Under this verification condition, the spacing is allowed to adjust with higher flexibility.

All tests has passed. I consider this change is safe. Because the function <code>sliding_window_array</code> also has nothing to to with <code>window_size</code> during its call in <code>extended_search_area_piv</code>.

Here is its usage:
<code># We implement the new vectorized code</code>
<code>aa = sliding_window_array(frame_a, search_area_size, overlap)</code>
<code>bb = sliding_window_array(frame_b, search_area_size, overlap)</code>

## Summary by Sourcery

Bug Fixes:
- Fix the overlap verification condition to allow overlap to be smaller than the search_area_size instead of the window_size.

### CODE REVIEW

**Comment by alexlib** [comment]
Dear @JUDEKEPA - could you please explain in PIV terms why would we need an overlap larger than the window size? Even window size overlap means that we just duplicate the same particles over and over again, creating huge oversampling. Raffel's book recommends .25 to .5 overlap, and I agree this is the most recommended case. I'd like to see some cases where this large overlap is beneficial.

**Comment by JUDEKEPA** [comment]
Dear @alexlib - actually I am working on using the Digital Image Correlation (DIC) method to observe some phenomenon in metal microstructure. And we need very large overlap to get a fine and dense displacement field. It is really useful in our work but I did not realise in PIV terms the large overlap is not necessary.

However, the other thing promotes me to change this setting is that, when I initially learned to use OpenPIV, I tried to use different values for window_size, search_area_size, and overlap. When I was using a large overlap I received the error message: 'ValueError("Overlap has to be smaller than the window_size")'. It is really easy for people to think that the overlap value is interacting with window_size instead of search_area_size. I tried to calculate the size of displacement field by hand based on the parameters, and I found the size of displacement field calculated rightly when the overlap value is interacting with search_area_size. I feel this change may be better for people to understand when they encounter with such error.

I am not an expert in PIV, so your opinion is more important whether the change should be made.

**Comment by alexlib** [comment]
> Dear @alexlib - actually I am working on using the Digital Image Correlation (DIC) method to observe some phenomenon in metal microstructure. And we need very large overlap to get a fine and dense displacement field. It is really useful in our work but I did not realise in PIV terms the large overlap is not necessary.
> 
> However, the other thing promotes me to change this setting is that, when I initially learned to use OpenPIV, I tried to use different values for window_size, search_area_size, and overlap. When I was using a large overlap I received the error message: 'ValueError("Overlap has to be smaller than the window_size")'. It is really easy for people to think that the overlap value is interacting with window_size instead of search_area_size. I tried to calculate the size of displacement field by hand based on the parameters, and I found the size of displacement field calculated rightly when the overlap value is interacting with search_area_size. I feel this change may be better for people to understand when they encounter with such error.
> 
> I am not an expert in PIV, so your opinion is more important whether the change should be made.

No problem that OpenPIV would also be useful for DIC. However, please create a Jupyter notebook with a test and some demo images that demonstrate this change's effect and influence. It wouldn't be very harmful if the backward compatibility is removed, but we do need to remind our users not to use unrealistic settings for PIV results. Some users get weird results using our software with the settings we never planned to use together and then "blame" the software for the results. Error message today is both software protection from failure and user protection from misuse of the PIV software :)

**Comment by JUDEKEPA** [comment]
> No problem that OpenPIV would also be useful for DIC. However, please create a Jupyter notebook with a test and some demo images that demonstrate this change's effect and influence. It wouldn't be very harmful if the backward compatibility is removed, but we do need to remind our users not to use unrealistic settings for PIV results. Some users get weird results using our software with the settings we never planned to use together and then "blame" the software for the results. Error message today is both software protection from failure and user protection from misuse of the PIV software :)

Totally agree. I made a showcase in jupyter notebook, the link is [here](https://github.com/JUDEKEPA/openpiv-python/blob/master/Example%20for%20overlap%20setting%20change.ipynb). I add some explanation at the top of blocks.

**Comment by alexlib** [comment]
Great @JUDEKEPA please move the notebook to the /openpiv/tutorials or /openpiv/tests/ where other notebooks are and send a message to the openpiv-users forum so people know about the change and its rationale. Thanks for the contribution.

**Comment by JUDEKEPA** [comment]
@alexlib I have moved the notebook to the /openpiv/tutorials and sent a request to join the openpiv users google group. I will send a message once I have joined the group.

**Comment by alexlib** [comment]
Great, thanks. Sorry I forgot to ask to complete the procedure by a) adding a unit test b) confirming all tests pass 
@JUDEKEPA

**Comment by JUDEKEPA** [comment]
@alexlib I have run the all tests under <code>tests/</code> folder. All 35 items passed. I added one test item in <code>test_process.py</code>, and I chose three tricky values for overlap to ensure the dimension of u and v is normal. I attached report here. [test_results.txt](https://github.com/user-attachments/files/17810674/test_results.txt)

Please check if everything is alright.

**Review by alexlib — APPROVED** [review]

**Comment by JUDEKEPA** [comment]
Thank you for your effort on OpenPIV. I'll try to contribute more. Please tell me if the change makes anything strange or unstable.

**Pull request merged**
