### PR TITLE
Replace nans patch

### PR DESCRIPTION
**Pull request by JohnLunzer**
Seems to be some changes @alexlib made in here... new to git so not sure how to remove them (tried several times). Anyway, my improvements to replace_nans is here. 

Edit: Now only my changes are here... so weird, but everything looks to be in order.

### CODE REVIEW

**Comment by alexlib** [comment]
Great piece of work. We only need a bit of documentation: what are the different kernels (inverse distance? disk? ) and how to use those (a working example as IPython notebook maybe? ) 

Thanks

**Comment by alexlib** [comment]
Great work. 

We would appreciate if you could add a short introduction to those kernels (inverse distance? disk?) what are the advantages/disadvantages and maybe a short example (better if IPython notebook)

Thanks in advance @JohnLunzer

**Comment by alexlib** [comment]
would you join us on https://groups.google.com/forum/#!forum/openpiv-users ?

**Comment by JohnLunzer** [comment]
Sorry for the mess, git still confounds me. I do not think I'll have the bandwidth in the near future to put together examples or a notebook. I've documented the methods in the docstring so at least people should be able to tell what they do without looking at the code which should help them make a decision on what to use. 

I haven't done nearly exhaustive enough testing to give the disadvantages or advantages. I definitely see a difference in my test cases but I have no truth to test against and little time to generate test data. I was driven to create these kernels by anecdotal advice: "even is better than uneven" and "closer is more relevant, farther less". In (unrelated) 2D median filtering I see artifacts caused by square kernels but when I use a disk kernel the artifacts vanish, my conclusion: disk shaped kernels reduce artifacts. 

One result I found interesting is that disk and distance kernels create similar results when allowed a moderate number of iterations (15). This told me hold off on generating a Gaussian kernel.

I'm sure this isn't sufficient commentary. In the absence of my own time I would leave it to the user to discover which method works best for them.

**Comment by alexlib** [comment]
This is fine. Could you please share those cases where you see the advantage? this will at least help others to see if they move in the same direction? 
and thanks again @JohnLunzer

**Comment by JohnLunzer** [comment]
Some things will have to wait. I have found an error in the replace_nans function (prior to my alterations) which compromises the quality of the inpainting. I have to step away from the problem so I can clear my head.

**Comment by JohnLunzer** [comment]
Okay, I've made the last of my changes (hopefully). The "error" I found in the replace_nans function was actually more of a "leak". Each nan was getting filtered and then added immediately back into the filled array and subsequent pixels would see that newly filtered pixel on the same iteration. This leak produced some nasty artifacts. The new flow uses a 1d array with the length of how nans there are and fills this array with each respective filtered pixel. At the end of the iteration each of this pixels is written to the array. Using this method a second "filled" array is not necessary, the copied array passed to the function is enough. This reduced the memory use of the function significantly.

Use cases:

I can't recommend the square "localmean" kernel at 1pixel radius in any situation. It creates jagged edges at the center of groups of NaN pixels. My current recommendation is the "disk" kernel with radius 2. This creates a "reach" similar to that of "localmean" at radius 1. The disk and distance kernels in general follow contours of groups of NaN pixels better. With a large radius the choice of kernel matters less. I do not recommend a kernel radius much above 7 as you start to end up with defined edges in the smaller groups of NaN pixels. Your radius will somewhat depend on your situation but lower radiuses are generally safer. 

The radius for "localmean" and "disk" are not directly comparable because the kernels "reach" differently. For disk a radius of 5 means 5 without exception. For localmean a radius of 5 actually means the corners of kernels reach out roughly 7 pixels, just use Pythagoras if you're trying to compare results of each. 

Lastly, distance and disk produce almost identical results, especially as the radius gets larger. "distance" creates slightly harder edges. I had no good reason to take it out or leave it in so I decided to leave it.

**Comment by JohnLunzer** [comment]
There is one situation where I would promote the use of the square kernel with radius 1, that is when performance is of the utmost importance. localmean radius 1 is still the faster kernel. I haven't done extensive timing tests. My conclusion is that the additional time is worth the added quality of the disk kernel. In documentation the user could be provided this information if they only care about speed.

**Comment by alexlib** [comment]
Thanks. So I'll merge it and add a comment.

**Pull request merged**
