### PR TITLE
added requirements.txt

### PR DESCRIPTION
**Pull request by alexlib**

### CODE REVIEW

**Comment by petebachant** [comment]
If this file is meant to be used with Conda, maybe an `environment.yml` file would be better.

**Comment by alexlib** [comment]
I'd be very glad if you show me how to build conda installation and use environment.yml. so far we used pypy and `pip install` and requirements.txt should be helpful there.

**Comment by petebachant** [comment]
Here's a sample of what could go in `environment.yml`:

```yaml
name: openpiv
dependencies:
- h5py=2.6.0=np110py35_0
- hdf5=1.8.15.1=vc14_4
- idna=2.1=py35_0
- imagesize=0.7.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython-notebook=4.0.4=py35_3
- ipython-qtconsole=4.0.1=py35_4
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jupyter=1.0.0=py35_2
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- matplotlib=1.5.1=np110py35_0
- nose=1.3.7=py35_0
- notebook=4.2.0=py35_0
- numpy=1.10.4=py35_0
- pip=8.1.1=py35_1
- python=3.5.1=4
- scipy=0.17.0=np110py35_1
- seaborn=0.7.0=py35_0
- setuptools=20.7.0=py35_0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
```

Note how you can differentiate which packages require pip to install from PyPI. 

When `environment.yml` is present in the working directory, users can create the environment with

    conda env create

then activate it with

    source activate openpiv

**Comment by alexlib** [comment]
looks great. would you submit a pull request so we can test and push upstream? thanks

**Comment by alexlib** [comment]
this PR is closed, overwritten by the environment.yml

**Pull request closed without merging**
