### PR TITLE
version 0.23.2

### PR DESCRIPTION
**Pull request by alexlib**
This version contains several new features and it breaks some code again:
1. `windef.multipass` is now similar to `firstpass` in the sense that it does not do internal validation or smoothing, everything is external to it, e.g. in `windef.piv`
2. image_mask created by `dynamic_masking` can be converted to `mask_coords` of an approximate polygon and used as a mask for the velocities. we use numpy.ma.MaskedArray for masking the data
3. new Jupyter notebook presents the test case with von Karman vortices in a cylinder wake from PIVLab - we're going to run this for a large set to compare
4. seems that there was a bug in `windef` and that lead to non-replaced vectors that propagated into the smaller windows. That was sort of a problem with the robustness probably.

### CODE REVIEW

**Comment by alexlib** [comment]
@eguvep - please see this branch, don't merge for sure - it'll break some of your calls to multipass. all the validation and outlier replacement options are not in multipass anymore and removed from the file.

**Review by eguvep — APPROVED** [review]
No problem, Alex. Just finish all cleanup works and I will adapt the GUI with a few days delay. Thanks for notifying me!

**Comment by alexlib** [comment]
@eguvep @TKaeufer please see if the changes are clear. Any objections to pull request?

**Comment by TKaeufer** [comment]
Dear Alex, sorry for the late reply. Currently, I have very little time. It might take me a while till I can have a proper look.

**Comment by alexlib** [comment]
> Dear Alex, sorry for the late reply. Currently, I have very little time. It might take me a while till I can have a proper look.



> Dear Alex, sorry for the late reply. Currently, I have very little time. It might take me a while till I can have a proper look.

Don't be sorry, all is fine. We do our tests. and we can always go back with the development if something is broken

**Pull request merged**
