### PR TITLE
Add more instructions to tutorial 1

### PR DESCRIPTION
**Pull request by gui-miotto**
This PR add more text to tutorial 1, to give the reader a better understanding of what each function does.

### CODE REVIEW

**Comment by alexlib** [comment]
thanks @gui-miotto

**Comment by gui-miotto** [comment]
My pleasure.

**Comment by gui-miotto** [comment]
Hi @alexlib , the documentation hasn't been updated.
I thought readthedocs would build the documentation automatically once you pushed something to the repo...
Do you know what is happening?

**Comment by alexlib** [comment]
Send please the link and maybe a screenshot of what is wrong. Maybe I missed something.

**Comment by gui-miotto** [comment]
Here:
https://openpiv.readthedocs.io/en/latest/src/tutorial1.html
This notebook is still the old version.

**Comment by alexlib** [comment]
Got it. There is a misunderstanding - there are two tutorial1.ipynb files, one in the /examples and one in the /docs. We updated the one in /examples, i guess and we need to copy it to the /docs and render it with sphinx. Can you please do it and send a new pull request? 
Thanks

**Comment by alexlib** [comment]
See the new build on read the docs. 

Build #13876092

**Comment by gui-miotto** [comment]
Now, it is there. Thanks.
:-)

**Pull request merged**
