### PR TITLE
Add environment.yml for use with conda

### PR DESCRIPTION
**Pull request by petebachant**
Based on discussion in #51. Currently this doesn't work, at least on Windows. I am getting this error:

```
C:\Temp\openpiv-python>conda env create
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
.Solving package specifications: .
Error:  Packages missing in current win-64 channels:
  - freetype 2.5.5 0
  - jbig 2.1 0
  - jpeg 8d 1
  - libtiff 4.0.6 1
  - openssl 1.0.2g 0
  - pyqt 4.11.4 py27_1
  - qt 4.8.7 1
  - readline 6.2 2
  - sqlite 3.9.2 0
  - tk 8.5.18 0
  - xz 5.0.5 1
```

@alexlib, are these specific versions hard dependencies, and are any of them only available via `pip`?

### CODE REVIEW

**Comment by alexlib** [comment]
It's something with windows, on Mac I have no problem. 

```
Alexs-MacBook-Pro-2:openpiv-python-conda-env alex$ conda env create -n openpiv
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
.Solving package specifications: .........
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate openpiv
#
# To deactivate this environment, use:
# $ source deactivate
#
Alexs-MacBook-Pro-2:openpiv-python-conda-env alex$ source activate openpiv
discarding /Users/alex/anaconda/bin from PATH
prepending /Users/alex/anaconda/envs/openpiv/bin to PATH
(openpiv)Alexs-MacBook-Pro-2:openpiv-python-conda-env alex$
``` 

I do not know what to do - I typically install it all with anaconda and I'd assume these packages are included in the anaconda package list.

**Comment by petebachant** [comment]
If I remove the specific build versions, things get a bit better, but there are still three unavailable packages:

```
C:\Temp\openpiv-python>conda env create
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .
Error:  Packages missing in current win-64 channels:
  - jbig 2.1*
  - readline 6.2*
  - xz 5.0.5*
```

**Comment by alexlib** [comment]
Can you see please test if the openpiv-python would work from the Jupyter notebook - I think this was the part that requires readline and other packages. Otherwise we do not need it and openpiv-python should work. Unfortunately we are also not sufficiently testing the software, so it's difficult to say which parts might not work.

**Comment by petebachant** [comment]
I was able to build the extensions with this env on Windows, but I will need to do some more testing to see if I can use it in the Notebook:

```yaml
dependencies:
- cycler=0.10.0=py27_0
- h5py=2.6.0=np111py27_0
- hdf5=1.8.15.1=vc9_4
- jpeg=8d=vc9_0
- libpng=1.6.17=vc9_1
- libtiff=4.0.6=vc9_1
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.1=0
- msvc_runtime=1.0.1=vc9_0
- nose=1.3.7=py27_0
- numpy=1.11.0=py27_0
- openssl=1.0.2g=vc9_0
- pandas=0.18.0=np111py27_0
- pip=8.1.1=py27_1
- pyparsing=2.1.1=py27_0
- pyqt=4.11.4=py27_5
- python=2.7.11=4
- python-dateutil=2.5.2=py27_0
- pytz=2016.3=py27_0
- qt=4.8.7=vc9_7
- scipy=0.17.0=np111py27_1
- seaborn=0.7.0=py27_0
- setuptools=20.7.0=py27_0
- sip=4.16.9=py27_2
- six=1.10.0=py27_0
- tk=8.5.18=vc9_0
- vs2008_runtime=9.00.30729.1=0
- vs2010_runtime=10.00.40219.1=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_2
```

Is there an example that tests almost all the functionality of OpenPIV?

**Comment by alexlib** [comment]
all the examples: https://github.com/OpenPIV/openpiv-python/tree/master/openpiv/examples 
include Ipython notebooks

**Comment by petebachant** [comment]
Tutorial 2 gives this error, since it depends on one of your local files:

```
IOErrorTraceback (most recent call last)
<ipython-input-2-703478f0de84> in <module>()
----> 1 frame_a  = openpiv.tools.imread( '/Users/alex/Downloads/Movie1_Scene1_Import VIDEO_079.png' )
      2 frame_b  = openpiv.tools.imread( '/Users/alex/Downloads/Movie1_Scene1_Import VIDEO_080.png' )

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\openpiv-0.20.1-py2.7-win-amd64.egg\openpiv\tools.pyc in imread(filename, flatten)
    121     """
    122 
--> 123     return io.imread( filename, as_grey = True)
    124 
    125 def imsave( filename, arr ):

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\skimage\io\_io.pyc in imread(fname, as_grey, plugin, flatten, **plugin_args)
     59 
     60     with file_or_url_context(fname) as fname:
---> 61         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     62 
     63     if not hasattr(img, 'ndim'):

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\skimage\io\manage_plugins.pyc in call_plugin(kind, *args, **kwargs)
    209                                (plugin, kind))
    210 
--> 211     return func(*args, **kwargs)
    212 
    213 

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\skimage\io\_plugins\pil_plugin.pyc in imread(fname, dtype, img_num, **kwargs)
     33     """
     34     if isinstance(fname, string_types):
---> 35         with open(fname, 'rb') as f:
     36             im = Image.open(f)
     37             return pil_to_ndarray(im, dtype=dtype, img_num=img_num)

IOError: [Errno 2] No such file or directory: '/Users/alex/Downloads/Movie1_Scene1_Import VIDEO_079.png'
```

**Comment by petebachant** [comment]
The masking tutorial gives this error:

```
TypeErrorTraceback (most recent call last)
<ipython-input-5-a4c5286b987a> in <module>()
      1 # masking using not optimal choice of the methods or parameters:
----> 2 masked_a = openpiv.preprocess.dynamic_masking(frame_a,method='edges',filter_size=7,threshold=0.005)
      3 masked_b = openpiv.preprocess.dynamic_masking(frame_b,method='intensity',filter_size=3,threshold=0.0)
      4 imshow(np.c_[masked_a,masked_b],cmap='gray')

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\openpiv-0.20.1-py2.7-win-amd64.egg\openpiv\preprocess.pyc in dynamic_masking(image, method, filter_size, threshold)
     75         bw = (blur_edges > threshold)
     76         bw = binary_fill_holes(bw)
---> 77         imcopy -= blurback
     78         imcopy[bw] = 0.0
     79     elif method is 'intensity':

TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
```

**Comment by petebachant** [comment]
The mulitpass tutorial gives this error:

```
ValueErrorTraceback (most recent call last)
<ipython-input-2-9a66a4bb6451> in <module>()
      1 #u, v, sig2noise = openpiv.process.extended_search_area_piv( frame_a, frame_b, window_size=24, overlap=12, dt=0.02, search_area_size=64, sig2noise_method='peak2peak' )
----> 2 u, v, sig2noise = openpiv.pyprocess.piv( frame_a, frame_b, window_size=32, overlap=8, dt=.1, sig2noise_method='peak2peak' )
      3 x, y = openpiv.process.get_coordinates( image_size=frame_a.shape, window_size=32, overlap=8 )

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\openpiv-0.20.1-py2.7-win-amd64.egg\openpiv\pyprocess.pyc in piv(frame_a, frame_b, window_size, overlap, dt, corr_method, subpixel_method, sig2noise_method, nfftx, nffty, width)
    460 
    461     # transform the arrray into a more covenient form for looping
--> 462     windows_a = moving_window_array( frame_a, window_size, overlap )
    463     windows_b = moving_window_array( frame_b, window_size, overlap )
    464 

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\openpiv-0.20.1-py2.7-win-amd64.egg\openpiv\pyprocess.pyc in moving_window_array(array, window_size, overlap)
    117     shape = ( int((shape[0] - window_size)/(window_size-overlap))+1, int((shape[1] - window_size)/(window_size-overlap))+1 , window_size, window_size)
    118 
--> 119     return numpy.lib.stride_tricks.as_strided( array, strides=strides, shape=shape ).reshape(-1, window_size, window_size)
    120 
    121 def find_first_peak ( corr ):

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\numpy\lib\stride_tricks.pyc in as_strided(x, shape, strides, subok)
     46     if strides is not None:
     47         interface['strides'] = tuple(strides)
---> 48     array = np.asarray(DummyArray(interface, base=x))
     49 
     50     if array.dtype.fields is None and x.dtype.fields is not None:

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\numpy\core\numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

ValueError: negative dimensions are not allowed
```

**Comment by petebachant** [comment]
The `BarakEvenChen` tutorial gives this error:

```
IOErrorTraceback (most recent call last)
<ipython-input-2-9ef598cbc428> in <module>()
----> 1 frame_a  = io.imread('/Users/alex/Downloads/1/PIC # 50015.tif')
      2 frame_b  = io.imread('/Users/alex/Downloads/1/PIC # 50016.tif')
      3 
      4 # for whatever reason the shape of frame_a is (3, 284, 256)
      5 # so we first tranpose to the RGB image and then convert to the gray scale

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\skimage\io\_io.pyc in imread(fname, as_grey, plugin, flatten, **plugin_args)
     59 
     60     with file_or_url_context(fname) as fname:
---> 61         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     62 
     63     if not hasattr(img, 'ndim'):

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\skimage\io\manage_plugins.pyc in call_plugin(kind, *args, **kwargs)
    209                                (plugin, kind))
    210 
--> 211     return func(*args, **kwargs)
    212 
    213 

C:\Users\Pete\Anaconda3\envs\openpiv\lib\site-packages\skimage\io\_plugins\tifffile_plugin.pyc in imread(fname, dtype, **kwargs)
     27     if 'img_num' in kwargs:
     28         kwargs['key'] = kwargs.pop('img_num')
---> 29     with open(fname, 'rb') as f:
     30         tif = TiffFile(f)
     31         return tif.asarray(**kwargs)

IOError: [Errno 2] No such file or directory: '/Users/alex/Downloads/1/PIC # 50015.tif'
```

**Comment by petebachant** [comment]
Just setup Travis to use Conda for Python libs, so the env is created and tested, though the test suite needs to be expanded for sure! Maybe take some of the code from the tutorials?

**Pull request merged**
