### PR TITLE
Phase separation feature

### PR DESCRIPTION
**Pull request by erfan-mtr**
Hi

My colleague and I have implemented a code for separating phase images of two-phase flows using image processing methods (e.g. separating image of solid phase particles from PIV tracer prticles). We are doing this as a part of our university project.

These image processing methods include:

- *Opening* morphology filter  
-  *Median filter* method described by Kiger & Pan (full reference in comments)
- An image segmentation-based method proposed by Khalitov & Longmire (full reference in comments)

This PR includes a python module (`phase_separation.py`) and a demo notebook (`phase_separation.ipynb`).

We hope you find it good enough.

### CODE REVIEW

**Comment by alexlib** [comment]
Dear @erfan-mtr 

Thanks a lot for this contribution. It looks good. I still have to get into details of it, but on the first sight it’s an excellent feature. I am only concerned about the OpenCV requirements for the installation. We already have difficulty to handle all the complexity of the installation by pip because of Cython and so on and it’s rather difficult task for non-programmers like us. 
Is it possible to think together about a different implementation using, e.g. scikit-image (Which is also requiring installation) or the tools that are already included in the openpiv-python? 
Another option that I see is that we open a repository of openpiv-features or openpiv-extensions and add your work there. We will then promote it on the website, forum, etc. and explain how would one a) install openpiv for all the standard stuff, b) install extensions and runs your example. This will allow us to leave the OpenCV installation as optional only for those users that need it. 

Looking forward to hear your opinion, 
Alex @alexlib

**Comment by erfan-mtr** [comment]
Thanks for the feedback, Alex. I looked into scikit-image and scipy.ndimage docs, and they seem to cover the functionalities needed for this feature. I have less experience using them but I'll give it a try.

**Comment by alexlib** [comment]
Don’t get me wrong - opencv-Python is easy to install with pip.
I just think how to make installation less cumbersome as not many need this feature.
Maybe the right way is to make both dynamic_masking and phase_separation using the same packages.

________________________________

**Comment by alexlib** [comment]
> Thanks for the feedback, Alex. I looked into scikit-image and scipy.ndimage docs, and they seem to cover the functionalities needed for this feature. I have less experience using them but I'll give it a try.

see an example in https://github.com/OpenPIV/openpiv-python/blob/master/openpiv/preprocess.py

**Comment by erfan-mtr** [comment]
Hi again. I have dropped dependency on OpenCV. Thanks.

**Comment by alexlib** [comment]
> Hi again. I have dropped dependency on OpenCV. Thanks.

+1
This is absolutely great @erfan-mtr 

Could we please just add a demo run of openpiv-python ? I understand that now we can run in the same notebook PIV just on the tracers. Would it be possible as a demo notebook? 

Thanks 

If you want, i have such data. Unfortunately I don't think that PIV will work on the large particles which have to be tracked (by simple nearest neighbour, but not PIV).

**Comment by erfan-mtr** [comment]
That’s okay. I think I can do that with artificial images but if you have some real world ones that you could share, that'd make for a better demo.

**Comment by erfan-mtr** [comment]
So, should I go with my artificial images?

They are generated with a very simple code I wrote for some basic testing. I doubt they resemble real-life images very well. (There's no noise, lighting is uniform, all particles are spherical, etc.)

I just want to make sure whether should I start with those images, or you're going to send me some nicer data.

**Comment by alexlib** [comment]
> So, should I go with my artificial images?
> 
> They are generated with a very simple code I wrote for some basic testing. I doubt they resemble real-life images very well. (There's no noise, lighting is uniform, all particles are spherical, etc.)
> 
> I just want to make sure whether should I start with those images, or you're going to send me some nicer data.

sorry, took longer than expected to find the images.

**Comment by alexlib** [comment]
> So, should I go with my artificial images?
> 
> They are generated with a very simple code I wrote for some basic testing. I doubt they resemble real-life images very well. (There's no noise, lighting is uniform, all particles are spherical, etc.)
> 
> I just want to make sure whether should I start with those images, or you're going to send me some nicer data.

maybe my data is not nicer than yours, so please go ahead with synthetic if my images are not suitable.

**Comment by erfan-mtr** [comment]
Hi

I had some challenges getting the code to work with the image you uploaded. Anyway, the challenge was constructive and led to  some improvements in the code.

Now we have a better demo that includes the actual PIV process. As a side note, I wasn't sure about scale & dt (I'm a bit curious to know what image it actually is :). Anyway, I had to guesstimate those values to be 2500px/meter and 20ns. Please correct me if it's too off.

**Comment by alexlib** [comment]
@erfan-mtr - thanks for the contribution. are you looking for the next challenge? I have a couple :)

**Comment by alexlib** [comment]
> Hi
> 
> 
> 
> I had some challenges getting the code to work with the image you uploaded. Anyway, the challenge was constructive and led to  some improvements in the code.
> 
> 
> 
> Now we have a better demo that includes the actual PIV process. As a side note, I wasn't sure about scale & dt (I'm a bit curious to know what image it actually is :). Anyway, I had to guesstimate those values to be 2500px/meter and 20ns. Please correct me if it's too off.

We have a paper in print so we will be able to show the real image values there. The velocity is about 20-50 m/s if I remember correctly. 
Thanks for the contribution.

**Comment by erfan-mtr** [comment]
> @erfan-mtr - thanks for the contribution. are you looking for the next challenge? I have a couple :)

Thanks, Alex. To be honest, right now I should focus on my university project before I hit the deadline. I found OpenPIV impressive and I hope I can contribute more in the future.

Best wishes,
Erfan

**Pull request merged**
