### PR TITLE
normalized_correlation

### PR DESCRIPTION
**Pull request by alexlib**
I tried to implement a normalized correlation scheme. The correlation values are no in range of [-1,1].

### CODE REVIEW

**Comment by alexlib** [comment]
@TKaeufer I cannot accept the pull request as now many tests fail 

run `pytest openpiv/test` from the `openpiv-python` directory and you'll see the failure.

**Comment by TKaeufer** [comment]
I see. Thanks for testing!

**Comment by TKaeufer** [comment]
@alexlib 
I changed the data type to float32. This was required by the tests to work. Before, the data type was changed inside the `normalize_intensity` function. I tested it on my PC, and now only those tests failed, which failed anyway.
Please tell me if the processing tests pass on your side as well. Thanks!

**Comment by alexlib** [comment]
> @alexlib
> I changed the data type to float32. This was required by the tests to work. Before, the data type was changed inside the `normalize_intensity` function. I tested it on my PC, and now only those tests failed, which failed anyway.
> Please tell me if the processing tests pass on your side as well. Thanks!

some tests pass, but the results do not look good. something in the code is broken, it's not only the dtype issue.

**Comment by alexlib** [comment]
and some tests fail, the one that I like most now is the test_display_vector_field that compares the old result to the new result as image to image. and it's rather clear that now we do not have a good set of vectors in the /examples/test1/ case

**Comment by alexlib** [comment]
> > @alexlib
> > I changed the data type to float32. This was required by the tests to work. Before, the data type was changed inside the `normalize_intensity` function. I tested it on my PC, and now only those tests failed, which failed anyway.
> > Please tell me if the processing tests pass on your side as well. Thanks!
> 
> some tests pass, but the results do not look good. something in the code is broken, it's not only the dtype issue.

I wonder about what you say "those that fail anyway"? please try `windef_refactoring` - it passes all the tests.

**Comment by alexlib** [comment]
furthermore, most of the results in the examples/notebooks/*.ipynb also fail. 
please check the window / np.std( ...) part

**Comment by TKaeufer** [comment]
Ok, thank you for your feedback. I most have messed something up on my testing and the different versions. Sorry for your inconvenience.

**Comment by TKaeufer** [comment]
Dear @alexlib 

I created a new environment for OpenPIV testing, unistalled all OpenPIV versions in any environment and istalled the latest version of OpenPIV in the testing environment. Then I replaced the pyprocess file int the testing environment with the modified version, that does the normalized cross correlation, and run the tests. My computer got stuck with  `test_display_vector_field` so I skipped it, but apart from that all tests pass.

grafik

I wonder why the tests pass now.

**Comment by alexlib** [comment]
After replacing the file you need to run 
Pip install -e . 

Or

python setup.py install 

Again. 

The pytest imports the installed files probably

**Comment by TKaeufer** [comment]
I am having issues with installing openpiv from source (Something with Visual Studio). However, I deleted the pycach and also manually set the import path of the validation test (which contains the sig2noise_ratio and used to fail) to the folder containing the modified pyprocess file and the test pass.

Do you think my approach solves the issue with importing the installed files?

**Comment by alexlib** [comment]
Indeed also for me only the tmp.png test fails as the result for the test1 case is different now. We need to make at least one test like this with a known, synthetic data (not simple one) to be able to get quickly a hint that some change does not work.

**Comment by TKaeufer** [comment]
Hi @alexlib ,
I reimplemented the circular cross-correlation and added an option for the normalized cross-correlation in the windef setup.

I did some minimal testing, but it seemed to work for me now. But please carefully test the changes. From a first glance, I would say that the normalized cross-correlation drastically increases the sig2noise ratio specific for the linear cross-correlation.
Please also have a close look at the displacement calculation from the peak position. It might be that I twisted something.  Also, now the second validation test fails.
But I have to focus on other things now and share my results with you so far.

Best regards,

Theo

**Comment by alexlib** [comment]
> Hi @alexlib ,
> I reimplemented the circular cross-correlation and added an option for the normalized cross-correlation in the windef setup.
> 
> I did some minimal testing, but it seemed to work for me now. But please carefully test the changes. From a first glance, I would say that the normalized cross-correlation drastically increases the sig2noise ratio specific for the linear cross-correlation.
> Please also have a close look at the displacement calculation from the peak position. It might be that I twisted something. Also, now the second validation test fails.
> But I have to focus on other things now and share my results with you so far.
> 
> Best regards,
> 
> Theo

Thanks a lot @TKaeufer . One "short" question relates to some convention that we need to agree about: 

in URAPIV, OpenPIV-Matlab and MATPIV - we conjugate the second image (b)
in PIVLab, windef and now in the new correlation functions you conjugate the first image (a). 
The difference is the direction of the shift (positive to negative). 
Shall we agree about it? 
How is it in JPIV? @eguvep

**Comment by eguvep** [comment]
In JPIV it is the first image: https://github.com/eguvep/jpiv/blob/a02613d8409556feb0bf92689aca91703bb03a32/src/jpiv2/PivUtil.java#L48

**Comment by alexlib** [comment]
I cannot find a good argument for the first image :) isn't it a shift of B
in respect to A what we're looking for?

**Comment by TKaeufer** [comment]
For me, both ways are fine.

**Comment by alexlib** [comment]
see #165  that contains also this work. 

the .conj() is on the first image :) of course, it should not matter much, but this is more consistent.

**Pull request closed without merging**
